int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _another_function(int n, int i);
int is_prime_number(int n);
int help_number(int n, int i);
int is_palindrome(char *s);
int len_st(char *s);
int help_p(char *s, int start, int end);
int wildcmp(char *s1, char *s2);
